# Generated by Django 4.2.13 on 2024-07-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
